apiVersion: batch/v1
kind: Job
metadata:
  name: tf-ps-{{cluster_name}}-{{ps_pod_index}}
spec:
  template:
    metadata:
      labels:
        name: tensorflow-ps-{{cluster_name}}-{{ps_pod_index}}
        role: ps
    spec:
      containers:
      - name: ps
        image: tensorflow/tensorflow:1.1.0
        resources:
          requests:
            memory: "1000M"
            cpu: "1000m"
          limits:
            memory: "1000M"
            cpu: "1000m"
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
{{ps_change_workplace_to_shared_folder}}
{{python_file_exists}}
ls;
{{python_codeblock_template}}
               "]
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        nfs:
          server: 192.168.0.10
          path: "/root/nfsFile"
      restartPolicy: Never
