apiVersion: batch/v1
kind: Job
metadata:
  name: tf-ps-1-2-{{ps_pod_index}}
spec:
  template:
    metadata:
      labels:
        name: tensorflow-ps{{ps_pod_index}}
        role: ps
    spec:
      containers:
      - name: ps
        image: tensorflow/tensorflow:1.1.0
        resources:
          requests:
            memory: "80M"
            cpu: "195m"
          limits:
            memory: "80M"
            cpu: "195m"
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
cd /mnt/dnn/;
ls;
{{python_codeblock_template}}
sleep 3600000;
               "]
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        nfs:
          server: 192.168.0.10
          path: "/root/nfsFile"
      restartPolicy: Never
