apiVersion: batch/v1
kind: Job
metadata:
  name: tf-ps-{{cluster_name}}-{{ps_pod_index}}
spec:
  template:
    metadata:
      labels:
        name: tensorflow-ps{{ps_pod_index}}
        role: ps
    spec:
      containers:
      - name: ps
        image: tensorflow/tensorflow:1.1.0
        resources:
          requests:
            memory: "800M"
            cpu: "800m"
          limits:
            memory: "800M"
            cpu: "800m"
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
if [ ! -d '/mnt/distribute-ML-demo-master-{{cluster_name}}/' ]; then curl ftp://192.168.0.10/distribute-ML-code.zip > qw.zip; unzip qw.zip; mv ./distribute-ML-code/ ./distribute-ML-demo-master-{{cluster_name}}/;mv ./distribute-ML-demo-master-{{cluster_name}}/ /mnt/;cd /mnt/distribute-ML-demo-master-{{cluster_name}}/; else cd /mnt/distribute-ML-demo-master-{{cluster_name}}/; fi;
ls;
{{python_codeblock_template}}
               "]
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        nfs:
          server: 192.168.0.10
          path: "/root/nfsFile"
      restartPolicy: Never
