apiVersion: v1
kind: Service
metadata:
  labels:
    name: tensorflow-ps{{ps_service_index}}
    role: ps
  name: tensorflow-ps-service{{ps_service_index}}
spec:
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: tensorflow-ps{{ps_service_index}}
    role: ps
