apiVersion: batch/v1
kind: Job
metadata:
  name: tf-wk-{{cluster_name}}-{{wk_pod_index}}
spec:
  template:
    metadata:
      labels:
        name: tensorflow-worker{{wk_pod_index}}
        role: worker
    spec:
      containers:
      - name: worker
        image: tensorflow/tensorflow:1.1.0
        resources:
          requests:
            memory: "800M"
            cpu: "800m"
          limits:
            memory: "800M"
            cpu: "800m"
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
cd /mnt/;
{{change_workspace_to_shared_folder}}
sleep 2;
ls;
{{python_codeblock_template}}
echo finish;
               "]
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        nfs:
          server: 192.168.0.10
          path: "/root/nfsFile"
      restartPolicy: Never
