apiVersion: batch/v1
kind: Job
metadata:
  name: tf-wk-1-2-{{wk_pod_index}}
spec:
  template:
    metadata:
      labels:
        name: tensorflow-worker{{wk_pod_index}}
        role: worker
    spec:
      containers:
      - name: worker
        image: 192.168.3.51:5000/admin/tensorflow/tensorflow:0.10.0
        resources:
          requests:
            memory: "800M"
            cpu: "1950m"
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
cd /mnt/;
{{change_workspace_to_shared_folder}}
ls ./;
python test_python.py;
{{python_codeblock_template}}
sleep 3600000;
               "]
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: my-nfs-pvc
      restartPolicy: Never
