apiVersion: batch/v1
kind: Job
metadata:
  name: tf-wk-1-2-2
spec:
  template:
    metadata:
      labels:
        name: tensorflow-worker2
        role: worker
    spec:
      containers:
      - name: worker
        image: tensorflow/tensorflow:1.1.0
        resources:
          requests:
            memory: "800M"
            cpu: "1950m"
          limits:
            memory: "800M"
            cpu: "1950m"
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
cd /mnt/dnn/;
python dnn3.py --ps_hosts=tensorflow-ps-service0.default.svc.cluster.local:2222 --worker_hosts=tensorflow-wk-service1.default.svc.cluster.local:2222,tensorflow-wk-service2.default.svc.cluster.local:2222 --job_name=worker --task_index=1 1>worker_log_1 2>worker_errlog_1;
sleep 3600000;
               "]
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        nfs:
          server: 192.168.0.10
          path: "/root/nfsFile"
      restartPolicy: Never
