apiVersion: batch/v1
kind: Job
metadata:
  name: tf-ps-1-2-0
spec:
  template:
    metadata:
      labels:
        name: tensorflow-ps0
        role: ps
    spec:
      containers:
      - name: ps
        image: tensorflow/tensorflow:1.1.0
        resources:
          requests:
            memory: "400M"
            cpu: "500m"
          limits:
            memory: "400M"
            cpu: "500m"
        ports:
        - containerPort: 2222
        command: ["/bin/sh", "-c"]
        args: ["
cd /mnt/;
python test_python.py;
sleep 3600000;
               "]
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        nfs:
          server: 192.168.0.10
          path: "/root/nfsFile"
      restartPolicy: Never
