apiVersion: v1
kind: Service
metadata:
  labels:
    name: tensorflow-ps0
    role: ps
  name: tensorflow-ps-service0
spec:
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: tensorflow-ps0
    role: ps
