apiVersion: v1
kind: Service
metadata:
  labels:
    name: tensorflow-worker1
    role: worker
  name: tensorflow-wk-service1
spec:
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: tensorflow-worker1
    role: worker
